### List shopping items
GET http://localhost:8080/shopping-items

### Create new shopping item
POST http://localhost:8080/shopping-items
Content-Type: application/json

{
    "name": "Pasta"
}

### Remove shopping item
DELETE http://localhost:8080/shopping-items/4fa70348-6677-4546-abae-6db9596b5d5c